package com.liwy.project.ws.cxf.cxfserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-27T15:36:19.977+08:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "CxfServiceImplService",
                  wsdlLocation = "http://localhost/Webservices/cxfService?wsdl",
                  targetNamespace = "http://cxf.ws.project.liwy.com/")
public class CxfServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.ws.project.liwy.com/", "CxfServiceImplService");
    public final static QName CxfServiceImplPort = new QName("http://cxf.ws.project.liwy.com/", "CxfServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/Webservices/cxfService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CxfServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost/Webservices/cxfService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CxfServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CxfServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CxfServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CxfServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CxfServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ICxfService
     */
    @WebEndpoint(name = "CxfServiceImplPort")
    public ICxfService getCxfServiceImplPort() {
        return super.getPort(CxfServiceImplPort, ICxfService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICxfService
     */
    @WebEndpoint(name = "CxfServiceImplPort")
    public ICxfService getCxfServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CxfServiceImplPort, ICxfService.class, features);
    }

}
