package com.liwy.project.ws.cxf.cxfserver;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-27T15:36:19.908+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://cxf.ws.project.liwy.com/", name = "ICxfService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICxfService {

    @WebMethod
    @RequestWrapper(localName = "map2List", targetNamespace = "http://cxf.ws.project.liwy.com/", className = "com.liwy.project.ws.cxf.cxfserver.Map2List")
    @ResponseWrapper(localName = "map2ListResponse", targetNamespace = "http://cxf.ws.project.liwy.com/", className = "com.liwy.project.ws.cxf.cxfserver.Map2ListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> map2List(
        @WebParam(name = "arg0", targetNamespace = "")
        com.liwy.project.ws.cxf.cxfserver.Map2List.Arg0 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "upStudent", targetNamespace = "http://cxf.ws.project.liwy.com/", className = "com.liwy.project.ws.cxf.cxfserver.UpStudent")
    @ResponseWrapper(localName = "upStudentResponse", targetNamespace = "http://cxf.ws.project.liwy.com/", className = "com.liwy.project.ws.cxf.cxfserver.UpStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.liwy.project.ws.cxf.cxfserver.User upStudent(
        @WebParam(name = "student", targetNamespace = "")
        com.liwy.project.ws.cxf.cxfserver.User student
    );

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://cxf.ws.project.liwy.com/", className = "com.liwy.project.ws.cxf.cxfserver.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://cxf.ws.project.liwy.com/", className = "com.liwy.project.ws.cxf.cxfserver.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
