
package com.liwy.project.ws.jws.secondserver;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISecondService", targetNamespace = "http://second.jws.ws.project.liwy.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISecondService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://second.jws.ws.project.liwy.com/", className = "com.liwy.project.ws.jws.secondserver.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://second.jws.ws.project.liwy.com/", className = "com.liwy.project.ws.jws.secondserver.SayHelloResponse")
    @Action(input = "http://second.jws.ws.project.liwy.com/ISecondService/sayHelloRequest", output = "http://second.jws.ws.project.liwy.com/ISecondService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "map2List", targetNamespace = "http://second.jws.ws.project.liwy.com/", className = "com.liwy.project.ws.jws.secondserver.Map2List")
    @ResponseWrapper(localName = "map2ListResponse", targetNamespace = "http://second.jws.ws.project.liwy.com/", className = "com.liwy.project.ws.jws.secondserver.Map2ListResponse")
    @Action(input = "http://second.jws.ws.project.liwy.com/ISecondService/map2ListRequest", output = "http://second.jws.ws.project.liwy.com/ISecondService/map2ListResponse")
    public List<String> map2List(
        @WebParam(name = "arg0", targetNamespace = "")
        com.liwy.project.ws.jws.secondserver.Map2List.Arg0 arg0);

    /**
     * 
     * @param student
     * @return
     *     returns com.liwy.project.ws.jws.secondserver.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upStudent", targetNamespace = "http://second.jws.ws.project.liwy.com/", className = "com.liwy.project.ws.jws.secondserver.UpStudent")
    @ResponseWrapper(localName = "upStudentResponse", targetNamespace = "http://second.jws.ws.project.liwy.com/", className = "com.liwy.project.ws.jws.secondserver.UpStudentResponse")
    @Action(input = "http://second.jws.ws.project.liwy.com/ISecondService/upStudentRequest", output = "http://second.jws.ws.project.liwy.com/ISecondService/upStudentResponse")
    public User upStudent(
        @WebParam(name = "student", targetNamespace = "")
        User student);

}
